spring:
  application:
    name: my-subcontract-template
  liquibase:
    change-log: classpath:/db/master.xml
    liquibase-schema: my_subcontract_template # pgsql使用
    default-schema: ${spring.liquibase.liquibase-schema} # pgsql使用
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/folio?currentSchema=${spring.liquibase.liquibase-schema}
    username: folio
    password: folio123
    hikari: #hikari数据库连接池
      pool-name: subcontract-hikari-tool
      minimum-idle: 20 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 100 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms